version: '3.4'

services:
  microservices.taxasdejuros.webapi:
    image: ${DOCKER_REGISTRY-}microservicestaxasdejuroswebapi
    build:
      context: .
      dockerfile: src/Microservices.TaxasDeJuros.WebApi/Dockerfile
