version: "3.0"
services:
  microservices-taxas-de-juros:
    image: sampaiobrenner/microservices-taxas-de-juros-webapi:latest
    ports: 
      - "8080:80"
    restart: unless-stopped
    networks: 
      - default
      
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24     